name: Clean Up Demo
description: Clean up a demo in the Canonical web team demo service.
inputs:
  demo-id:
    required: true
    description: The unique ID for this demo.

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v3
    - name: TODO actually do the cleanup
      shell: bash
      run: |
        echo "Remove the demo with id '${{ inputs.demo-id }}' from the plan"
