name: Demo Comment
description: Create or update a comment on a PR for the demo service.
inputs:
  demo-id:
    required: true
    description: The unique ID for this demo.
  status:
    required: true
    description: Either 'pending' (deployment in progress) or 'deployed' (demo is live).
  run-id:
    required: false
    description: The GitHub Actions run ID, used to link to the workflow run in the pending comment.

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        DEMO_ID: ${{ inputs.demo-id }}
        STATUS: ${{ inputs.status }}
        RUN_ID: ${{ inputs.run-id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const existingComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('<!-- demo_service -->')
          })

          const demoId = process.env.DEMO_ID;
          const status = process.env.STATUS;
          const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.RUN_ID}`;

          let body;
          if (status === 'pending') {
            body = `<!-- demo_service -->\n### <img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo\n⏳ Deployment in progress… [View workflow run](${runUrl})`;
          } else {
            // TODO: the URL needs to be updated to point at the real demo service.
            body = `<!-- demo_service -->\n### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo](https://${demoId}.example.com)\n✅ Demo deployed: https://${demoId}.example.com`;
          }

          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
          }
